update install script

diff --git a/bin/bin/install-composer b/bin/bin/install-composer
--- a/bin/bin/install-composer
+++ b/bin/bin/install-composer
@@ -1,8 +1,19 @@
-#!/bin/bash
+#!/bin/sh
+# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
 
-# https://getcomposer.org/download/
-
+EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
 php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-php composer-setup.php --install-dir=$HOME/bin --filename=composer
-php -r "unlink('composer-setup.php');"
+ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+then
+    >&2 echo 'ERROR: Invalid installer signature'
+    rm composer-setup.php
+    exit 1
+fi
+
+php composer-setup.php # --quiet
+RESULT=$?
+mv composer.phar composer
+rm composer-setup.php
+exit $RESULT
